version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bookmark_api
    networks:
      - freecodecamp
networks:
  freecodecamp: